### ISSUE TITLE
Feature: Move Live Map

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisit-materialui#1]

**Comment by rskidmore1** [comment]
## Description
Recreate Live Map with Material UI front end 

## Plan
Decide which page type in template to put the live Map into 

## Task List 

### Research 
- [ ] Decide what page type use 
- [ ] Can i just import the component and call it?
  - [ ] What happens to HTML in Material UI?

### Misc
- [ ] Install all libraries 

### Client 
- [ ] Move compoents 
  - [ ] google-map-react
  - [ ] express.js
- [ ] Call in Material page

### Server 
- [ ] Set up server code in npm 
- [ ] Create index.js
  - [ ] Create demo routes get

### Database 
- [ ] Set up postgres connection in npm
